[package]
name = "quivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "46.0.0"
csv = "1.2.2"
dyn-clone = "1.0.14"
